[[themes]]
name = "Catppuccin-mocha"
[themes.palette]
background = "#111111"
foreground = "#ffffff"
black = "#1e1e2e"
blue = "#89b4fa"
cyan = "#89dceb"
green = "#a6e3a1"
magenta = "#bfbfff"
red = "#f38ba8"
white = "#cdd6f4"
yellow = "#f9e2af"
bright_black = "#1e1e2e"
bright_blue = "#89b4fa"
bright_cyan = "#89dceb"
bright_green = "#a6e3a1"
bright_magenta = "#cba6f7"
bright_red = "#f38ba8"
bright_white = "#cdd6f4"
bright_yellow = "#f9e2af"

[themes.component_style]
selection = { fg = "#111111", bg = "#bfbfff", modifiers = ["Bold"] }
block_title = { fg = "Magenta", modifiers = ["Bold"] }
playback_track = { fg = "Magenta", modifiers = ["Bold"] }
playback_album = { fg = "#ffffff" }
playback_artists = { fg = "Magenta", modifiers = ["Bold"] }
playback_metadata = { fg = "#505050" }
playback_progress_bar = { bg = "#505050", fg = "#bfbfff" }
current_playing = { fg = "#ffffff", modifiers = ["Bold"] }
page_desc = { fg = "#505050", modifiers = ["Bold"] }
table_header = { fg = "#505050" }
border = {fg = "#bfbfff"}
playback_status = { fg = "Magenta", modifiers = ["Bold"] }
playlist_desc = { fg = "#ffffff" }

